### PR TITLE
Cspexam.md

### PR DESCRIPTION
**Pull request by akprathipati**
Goes over the AP CSP test! Also changed indentation for the 1st one.

### CODE REVIEW

**Comment by akprathipati** [comment]
Internet stuff

**Comment by akprathipati** [comment]
Internet added!

**Comment by akprathipati** [comment]
added more information

**Comment by nathanielCherian** [comment]
The checks failed because you kept some files under the /data directory. Please choose a subdirectory (gotchas, tricks, pbl...) to place your files in.

**Comment by akprathipati** [comment]
fixed

**Comment by nathanielCherian** [comment]
image

**Comment by nathanielCherian** [comment]
please move Exam.md to a subdirectory

**Comment by nathanielCherian** [comment]
You need to move Exam.md to a subdirectory, otherwise it will fail

**Comment by akprathipati** [comment]
I deleted Exam.md, will this work now? Sorry for the inconvenience!

**Comment by nathanielCherian** [comment]
There are some other things that are broken I will merge and try to fix later

**Comment by akprathipati** [comment]
Wait did I somehow screw it more? Im pretty sure I followed all the direction except the exam.md mishap.

**Comment by nathanielCherian** [comment]
okay, so it looks like for some of them the formatting is a couple spaces off. Apparently this throws error. I'll merge in anyway and fix manually, I saw you deleted some other files. Feel free to add those back in if you want

**Pull request merged**
